name: aws_whitepapers_guides
description: Amazon Web Services AWS Whitepapers, Technical Guides, Reference Material and Architectural Diagram

version: 1.1.0+10

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
  http:
  provider:
  shared_preferences:
  html:
  path_provider:
  flutter_pdfview: ^1.0.4
  flutter_downloader:
  shimmer:
  path:
  bottom_navy_bar:
  permission_handler:
  url_launcher:
  flutter_svg: ^0.18.1

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  json_model:
  build_runner:
  json_serializable:

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/img/icon.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/no_data.svg
    - assets/svg/no_bookmarks.svg
    - assets/svg/no_downloads.svg
    - assets/svg/no_internet.svg
    - assets/svg/no_search_items.svg
    - assets/svg/unknown_error.svg
    - assets/img/aws_whitepapers_banner.png

  fonts:
    - family: GFSDidot
      fonts:
        - asset: assets/fonts/GFSDidot-Regular.ttf

